var products = [
  {
    id: 'p001',
    name:'Schwinn Mark V Bike',
    category: 'Sporting Goods',
    subCategory: 'Bicycles',
    brand: 'Schwinn',
    store: 'Sports Land',
    description:'Schwinn\'s Mark V is a full-dress cruiser that nails the number one reason we ride bikes: fun. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 150,
    tags: 'sports sporting goods bicycles bikes frames recreation',
    img:'http://sicklerbikes.com/images/library/zoom/schwinn_MARV26_SND_13_z.jpg'
  },
  {
    id: 'p002',
    name: 'Sandisk 32GB USB Drive ',
    category: 'Electronics',
    subCategory: 'Storage',
    brand: 'Sandisk',
    store: '',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 32.75,
    tags: 'Sandisk Electronics storage usb drive thumb flash',
    img:'#'
  },
  {
    id: 'p003',
    name:'Honda Civic',
    category: 'Car',
    subCategory: 'Sedan',
    brand: 'Honda',
    store: 'Karl Malone Honda',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 15827,
    tags: 'honda civic sedan economy vehicle car',
    img:'#'
  },
  {
    id: 'p004',
    name:'Tom Ford square-rim glasses',
    category: 'Clothing and Accessories',
    subCategory: 'Eyewear',
    brand: 'Tom Ford',
    store: 'Positive Eye-Ons',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 119.85,
    tags: 'glasses eyeglasses vision tom ford',
    img:'#'
  },
  {
    id: 'p005',
    name:'13-inch MacBook Pro',
    category: 'Electronics',
    subCategory: 'Laptops',
    brand: 'Apple',
    store: 'Apple Store',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 1300,
    tags: 'apple macbook laptop 13-inch electronics computer',
    img:'#'
  },
  {
    id: 'p006',
    name:'15 in Dell Ultrabook',
    category: 'Electronics',
    subCategory: 'Laptops',
    brand: 'Dell',
    store: 'Best Buy',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 999.99,
    tags: 'dell ultrabook ultra laptop 15-inch 15 in electronics computer',
    img:'#'},
  {
    id: 'p007',
    name:'12 in Lenovo Thinkpad',
    category: 'Electronics',
    subCategory: 'Laptops',
    brand: 'Lenovo',
    store: 'Fry\'s',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 850,
    tags: 'lenovo thinkpad laptop 12-inch 12 in electronics computer',
    img:'#'
  },
  {
    id: 'p008',
    name:'1 ream of paper',
    category: 'School and Office Supplies',
    subCategory: 'Paper',
    brand: 'Dunder-Mifflin',
    store: 'Staples',
    description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 1.27,
    tags: 'paper ream dunder mifflin staples school office supplies',
    img:'#'
  },
  {
    id: 'p009',
    name:'Nike Roshe Running Shoe',
    category: 'Clothing and Accessories',
    subCategory: 'Footwear',
    brand: 'Nike',
    store: 'Nike Store',
    description:'Made for both running and everyday use. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 95.50,
    tags: 'shoes shoe nike footwear sneaker running rosche',
    img:'http://images.nike.com/is/image/DotCom/511881_A_V2?&$img=511881_023_A_PREM&$PDP_HERO$'
  },

  {
    id: 'p010',
    name:'Vans High-Tops Shoes',
    category: 'Clothing and Accessories',
    subCategory: 'Footwear',
    brand: 'Vans',
    store: 'Vans Store',
    description:'Classic pair of shoes from Vans. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 44.95,
    tags: 'shoes shoe vans footwear sneaker casual skateboarding high top',
    img:'http://images.vans.com/is/image/Vans/QG36BT-HERO?$583x583$'
  },
  {
    id: 'p011',
    name:'Spalding Indoor/Outdoor Basketball',
    category: 'Sporting Goods',
    subCategory: 'Basketball',
    brand: 'Spalding',
    store: 'Sports Land',
    description:'Spalding indoor-outdoor basketball. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    price: 27.00,
    tags: 'sports sporting goods ball basketball spalding court indoor outdoor',
    img:'http://thumbs1.ebaystatic.com/d/l225/m/m9jsV41Jk7HU6fBkgyd9W-g.jpg'
  }
]
var states = [
    { name: 'Alabama', abbreviation: 'AL'},
    { name: 'Alaska', abbreviation: 'AK'},
    { name: 'American Samoa', abbreviation: 'AS'},
    { name: 'Arizona', abbreviation: 'AZ'},
    { name: 'Arkansas', abbreviation: 'AR'},
    { name: 'California', abbreviation: 'CA'},
    { name: 'Colorado', abbreviation: 'CO'},
    { name: 'Connecticut', abbreviation: 'CT'},
    { name: 'Delaware', abbreviation: 'DE'},
    { name: 'District of Colubmia', abbreviation: 'DC'},
    { name: 'Florida', abbreviation: 'FL'},
    { name: 'Georgia', abbreviation: 'GA'},
    { name: 'Guam', abbreviation: 'GU'},
    { name: 'Hawaii', abbreviation: 'HI'},
    { name: 'Idaho', abbreviation: 'ID'},
    { name: 'Illinois', abbreviation: 'IL'},
    { name: 'Indiana', abbreviation: 'IN'},
    { name: 'Iowa', abbreviation: 'IA'},
    { name: 'Kansas', abbreviation: 'KS'},
    { name: 'Kentucky', abbreviation: 'KY'},
    { name: 'Louisiana', abbreviation: 'LA'},
    { name: 'Maine', abbreviation: 'ME'},
    { name: 'Marshall', abbreviation: 'MH'},
    { name: 'Maryland', abbreviation: 'MD'},
    { name: 'Massachusetts', abbreviation: 'MA'},
    { name: 'Michigan', abbreviation: 'MI'},
    { name: 'Minnesota', abbreviation: 'MN'},
    { name: 'Mississippi', abbreviation: 'MS'},
    { name: 'Missouri', abbreviation: 'MO'},
    { name: 'Montana', abbreviation: 'MT'},
    { name: 'Nebraska', abbreviation: 'NE'},
    { name: 'Nevada', abbreviation: 'NV'},
    { name: 'New Hampshire', abbreviation: 'NH'},
    { name: 'New Jersey', abbreviation: 'NJ'},
    { name: 'New Mexico', abbreviation: 'NM'},
    { name: 'New York', abbreviation: 'NY'},
    { name: 'North Carolina', abbreviation: 'NC'},
    { name: 'North Dakota', abbreviation: 'ND'},
    { name: 'Ohio', abbreviation: 'OH'},
    { name: 'Oklahoma', abbreviation: 'OK'},
    { name: 'Oregon', abbreviation: 'OR'},
    { name: 'Pennsylvania', abbreviation: 'PA'},
    { name: 'Puerto Rico', abbreviation: 'PR'},
    { name: 'Rhode Island', abbreviation: 'RI'},
    { name: 'South Carolina', abbreviation: 'SC'},
    { name: 'South Dakota', abbreviation: 'SD'},
    { name: 'Tennessee', abbreviation: 'TN'},
    { name: 'Texas', abbreviation: 'TX'},
    { name: 'Utah', abbreviation: 'UT'},
    { name: 'Vermont', abbreviation: 'VT'},
    { name: 'Virgin Islands', abbreviation: 'VI'},
    { name: 'Virginia', abbreviation: 'VA'},
    { name: 'Washington', abbreviation: 'WA'},
    { name: 'West Virginia', abbreviation: 'WV'},
    { name: 'Wisconsin', abbreviation: 'WI'},
    { name: 'Wyoming', abbreviation: 'WY' }
];
