var products = [
  {id:"p001",group:"men","brand":"Gap","category":"shoes","name":"Suede athletic trainers","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":39.95,"sizes":[5, 6, 7, 8, 9, 10, 11, 12, 13, 14],"tags":"men gap shoe tennis shoes athletic trainers","img":"images/gap-men-shoe-01.jpg"},
  {id:"p002",group:"men","brand":"Gap","category":"shoes","name":"Leather sneakers","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":44.95,"sizes": [5, 6, 7, 8, 9, 10, 11, 12, 13, 14],"tags":"men gap shoe shoes athletic sneakers leather","img": "images/gap-men-shoe-02.jpg"},
  {id:"p003",group:"men","brand":"Gap","category":"shoes","name":"Basic flip flops","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":19,"sizes":[5, 6, 7, 8, 9, 10, 11, 12, 13, 14],"tags":"men gap shoe flip flop flip-flop sandal","img":"images/gap-men-shoe-03.jpg"},
  {id:"p004",group:"men","brand":"Gap","category":"shirts","name":"Stripe crew slub t-shirt","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":16.95,"sizes":['small', 'medium', 'large', 'extra large'],"tags":"men gap shirt shirts tee t-shirt t stripe crew","img":"images/gap-men-shirt-01.jpg"},
  {id:"p005",group:"men","brand":"Gap","category":"shirts","name":"Soft henley shirt","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":24,"sizes":['small', 'medium', 'large', 'extra large'],"tags":"men gap henley shirt shirts long-sleeve long button","img":"images/gap-men-shirt-02.jpg"},
  {id:"p006",group:"men","brand":"Gap","category":"shirts","name":"Slub feeder stripe tee","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":21.95,"sizes":['small', 'medium', 'large', 'extra large'],"tags":"men gap stripe shirt shirts tee t-shirt t","img":"images/gap-men-shirt-03.jpg"},
  {id:"p007",group:"men","brand":"Gap","category":"pants","name":"Vintage wash straight-fit khakis","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":59.95,"sizes":{"width": [28, 29, 30, 31, 32, 33, 34, 36, 38, 40, 42], "length": [28, 29, 30, 31, 32, 33, 34]},"tags":"men gap khaki pants straight","img":"images/gap-men-pant-01.jpg"},
  {id:"p008",group:"men","brand":"Gap","category":"pants","name":"Herringbone slim fit pants","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":49.99,"sizes":{"width": [28, 29, 30, 31, 32, 33, 34, 36, 38, 40, 42], "length": [28, 29, 30, 31, 32, 33, 34]},"tags":"men gap pants slim herringbone","img":"images/gap-men-pant-02.jpg"},
  {id:"p009",group:"men","brand":"Gap","category":"pants","name":"Stretch 1969 slim fit jeans","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":64.95,"sizes":{"width": [28, 29, 30, 31, 32, 33, 34, 36, 38, 40, 42], "length": [28, 29, 30, 31, 32, 33, 34]},"tags":"men gap pants jean jeans slim 1969","img":"images/gap-men-pant-03.jpg"},
  {id:"p010",group:"men","brand":"Cotton On","category":"shoes","name":"Seattle gym boot high","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":15,"sizes":[5, 6, 7, 8, 9, 10, 11, 12, 13, 14],"tags":"men cotton on shoe shoes seattle casual high high-top","img":"images/cotton-men-shoe-01.jpg"},
  {id:"p011",group:"men","brand":"Cotton On","category":"shoes","name":"Joey shoe","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":21,"sizes":[5, 6, 7, 8, 9, 10, 11, 12, 13, 14],"tags":"men cotton on shoe shoes joey casual sneaker","img":"images/cotton-men-shoe-02.jpg"},
  {id:"p012",group:"men","brand":"Cotton On","category":"shoes","name":"Leather flip flops","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":18.95,"sizes":[5, 6, 7, 8, 9, 10, 11, 12, 13, 14],"tags":"men cotton on shoe shoes flip-flop flip flop sandal","img":"images/cotton-men-shoe-03.jpg"},

  {id:"p013",group:"men","brand":"Cotton On","category":"shirts","name":"Jack texture short sleeve button down","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":24.95,"sizes":['small', 'medium', 'large', 'extra large'],"tags":"men cotton on shirt shirts short short-sleeve button","img":"images/cotton-men-shirt-01.jpg"},
  {id:"p014",group:"men","brand":"Cotton On","category":"shirts","name":"Patterned Tee","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":11,"sizes":['small', 'medium', 'large', 'extra large'],"tags":"men cotton on shirt shirts short tee t-shirt","img":"images/cotton-men-shirt-02.jpg"},
  {id:"p015",group:"men","brand":"Cotton On","category":"shirts","name":"Tall crew tee","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":16,"sizes":['small', 'medium', 'large', 'extra large'],"tags":"men cotton on shirt shirts tall crew short tee t-shirt","img":"images/cotton-men-shirt-03.jpg"},
  {id:"p016",group:"men","brand":"Cotton On","category":"pants","name":"Slouch tapered chino","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":24.95,"sizes":{"width": [28, 29, 30, 31, 32, 33, 34, 36, 38, 40, 42], "length": [28, 29, 30, 31, 32, 33, 34]},"tags":"men cotton on pants tapered chino","img":"images/cotton-men-pant-01.jpg"},
  {id:"p017",group:"men","brand":"Cotton On","category":"pants","name":"Square cut chino","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":32,"sizes":{"width": [28, 29, 30, 31, 32, 33, 34, 36, 38, 40, 42], "length": [28, 29, 30, 31, 32, 33, 34]},"tags":"men cotton on pants square chino","img":"images/cotton-men-pant-02.jpg"},
  {id:"p018",group:"men","brand":"Cotton On","category":"pants","name":"Tapered carrot jean","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.","price":39.99,"sizes":{"width": [28, 29, 30, 31, 32, 33, 34, 36, 38, 40, 42], "length": [28, 29, 30, 31, 32, 33, 34]},"tags":"men cotton on pants jean jeans","img":"images/cotton-men-pant-03.jpg"}
];

var states = [
    { name: 'Alabama', abbreviation: 'AL'},
    { name: 'Alaska', abbreviation: 'AK'},
    { name: 'American Samoa', abbreviation: 'AS'},
    { name: 'Arizona', abbreviation: 'AZ'},
    { name: 'Arkansas', abbreviation: 'AR'},
    { name: 'California', abbreviation: 'CA'},
    { name: 'Colorado', abbreviation: 'CO'},
    { name: 'Connecticut', abbreviation: 'CT'},
    { name: 'Delaware', abbreviation: 'DE'},
    { name: 'District of Colubmia', abbreviation: 'DC'},
    { name: 'Florida', abbreviation: 'FL'},
    { name: 'Georgia', abbreviation: 'GA'},
    { name: 'Guam', abbreviation: 'GU'},
    { name: 'Hawaii', abbreviation: 'HI'},
    { name: 'Idaho', abbreviation: 'ID'},
    { name: 'Illinois', abbreviation: 'IL'},
    { name: 'Indiana', abbreviation: 'IN'},
    { name: 'Iowa', abbreviation: 'IA'},
    { name: 'Kansas', abbreviation: 'KS'},
    { name: 'Kentucky', abbreviation: 'KY'},
    { name: 'Louisiana', abbreviation: 'LA'},
    { name: 'Maine', abbreviation: 'ME'},
    { name: 'Marshall', abbreviation: 'MH'},
    { name: 'Maryland', abbreviation: 'MD'},
    { name: 'Massachusetts', abbreviation: 'MA'},
    { name: 'Michigan', abbreviation: 'MI'},
    { name: 'Minnesota', abbreviation: 'MN'},
    { name: 'Mississippi', abbreviation: 'MS'},
    { name: 'Missouri', abbreviation: 'MO'},
    { name: 'Montana', abbreviation: 'MT'},
    { name: 'Nebraska', abbreviation: 'NE'},
    { name: 'Nevada', abbreviation: 'NV'},
    { name: 'New Hampshire', abbreviation: 'NH'},
    { name: 'New Jersey', abbreviation: 'NJ'},
    { name: 'New Mexico', abbreviation: 'NM'},
    { name: 'New York', abbreviation: 'NY'},
    { name: 'North Carolina', abbreviation: 'NC'},
    { name: 'North Dakota', abbreviation: 'ND'},
    { name: 'Ohio', abbreviation: 'OH'},
    { name: 'Oklahoma', abbreviation: 'OK'},
    { name: 'Oregon', abbreviation: 'OR'},
    { name: 'Pennsylvania', abbreviation: 'PA'},
    { name: 'Puerto Rico', abbreviation: 'PR'},
    { name: 'Rhode Island', abbreviation: 'RI'},
    { name: 'South Carolina', abbreviation: 'SC'},
    { name: 'South Dakota', abbreviation: 'SD'},
    { name: 'Tennessee', abbreviation: 'TN'},
    { name: 'Texas', abbreviation: 'TX'},
    { name: 'Utah', abbreviation: 'UT'},
    { name: 'Vermont', abbreviation: 'VT'},
    { name: 'Virgin Islands', abbreviation: 'VI'},
    { name: 'Virginia', abbreviation: 'VA'},
    { name: 'Washington', abbreviation: 'WA'},
    { name: 'West Virginia', abbreviation: 'WV'},
    { name: 'Wisconsin', abbreviation: 'WI'},
    { name: 'Wyoming', abbreviation: 'WY' }
];
